#include "tc.hh"

namespace node {
  void set_ecodes (const Handle<Object> tmpl) {
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ESUCCESS);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ETHREAD);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EINVALID);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ENOFILE);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ENOPERM);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EMETA);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ERHEAD);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EOPEN);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ECLOSE);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ETRUNC);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ESYNC);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ESTAT);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ESEEK);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EREAD);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EWRITE);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EMMAP);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ELOCK);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EUNLINK); 
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ERENAME); 
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EMKDIR);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ERMDIR);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EKEEP);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, ENOREC);
    DEFINE_PREFIXED_CONSTANT(tmpl, TC, EMISC);
  }
  
  SUBMD_DECL(hdb) SUBMD_DECL(bdb) SUBMD_DECL(fdb) SUBMD_DECL(tdb) SUBMD_DECL(adb);
  ADDON_INIT(tc_all, SUBMD_INIT(hdb) SUBMD_INIT(bdb) SUBMD_INIT(fdb) SUBMD_INIT(tdb) SUBMD_INIT(adb));
}
